#
# Makefile for the FT5826S touchscreen driver.
#
# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_FOCAL_FT5826S) += focaltech_core.o focaltech_ctl.o focaltech_ex_fun.o focaltech_flash.o focaltech_gesture.o 
