/* Copyright Statement:
*This firmware are protected under relevant copyright laws,this information contained
*herein is confidential and proprietary to Goodix.
*
*GOODIX (C) 2013. All rights reserved.
*
*WARNING:The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
*please do not modify it manually!
*
*/

#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

#if GTP_HEADER_FW_UPDATE
unsigned char gtp_default_FW[] = {
	/* TODO:Puts your update firmware data here! */
#include "GT9271_1043_B61E.h"
};
#endif

#endif
